version: "3.1"

services:
  tserver_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: tserver_db
      MYSQL_ROOT_USER: jdvs
      MYSQL_USER: jdvs
      MYSQL_ROOT_PASSWORD: Mariaemma1520
      MYSQL_PASSWORD: Mariaemma1520
